language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

script:
- cargo clean
- cargo build
- cargo test

after_success: |
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
