---
version: "2"
services:
  some_container:
    image: ubuntu
    command: sleep infinity
    networks:
      - web
  whoami:
    image: emilevauge/whoami
    network_mode: "service:some_container"
    labels:
      - "traefik.backend=whoami"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
    network_doedel: "CULPER.AES_CBC_PAD.ZTx5f2laR79uDv8wDl9Quw==.Wy5EcGRJ2hh0Ogw5XwdLLQ=="
networks:
  web:
    external:
      name: traefik_webgateway